### PR TITLE
Support SapoPuny

### PR DESCRIPTION
**Pull request by ambs**
Hi

Added an extra service, SapoPuny (sl.pt).
It has a nice feature: it is only a host name, not a host and path.

Hope you like it.
Hope I edited everywhere it was needed.

Best
Alberto
(just for the record, PRC pull request)

### CODE REVIEW

**Comment by davorg** [comment]
Hi Alberto,

Thanks for your suggestion.

The upstream repo for this project is now at https://github.com/p5-shorten/www-shorten. You should send your pull request there.

However, the preferred way to support new services in WWW::Shorten is to bundle them into separate modules which get released to CPAN individually. See, for example, https://metacpan.org/pod/WWW::Shorten::Googl and https://metacpan.org/pod/WWW::Shorten::Bitly. So it would be better to release this as a separate distribution which requires WWW::Shorten.

**Comment by ambs** [comment]
On 17/03/16 07:40, Dave Cross wrote:
> Hi Alberto,
>
> Thanks for your suggestion.
>
> The upstream repo for this project is now at
> https://github.com/p5-shorten/www-shorten. You should send your pull
> request there.
>
> However, the preferred way to support new services in WWW::Shorten is to
> bundle them into separate modules which get released to CPAN
> individually. See, for example,
> https://metacpan.org/pod/WWW::Shorten::Googl and
> https://metacpan.org/pod/WWW::Shorten::Bitly. So it would be better to
> release this as a separate distribution which requires WWW::Shorten.

Damn, that way this doesn't count as a pull request :-)
But I will propose it upstream and see what is answered there.
Thank you

Alberto

**Comment by davorg** [comment]
Oh. I missed the bit where you said this came from the PRC. Sorry about that :-/

I'll email Neil and tell him what's going on.

**Comment by ambs** [comment]
No problem on that. Do not worry, I'll find something else to patch :)

**Pull request closed without merging**
